AWSTemplateFormatVersion: 2010-09-09
Description: >- 
  ElectricEye StackSet deploys an IAM Role with all possible ElectricEye permissions that trust a central security account for AWS Organizations-wide assessments
Parameters:
  # Security Account ID
  CentralSecurityAccount:
    Description: Account ID for your Security Account
    Type: String
Resources:
  #######
  # IAM #
  #######
  CrossAccountElectricEyeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CrossAccountElectricEyeRole
      Description: >-
        Allows the Central Security Account access to all AWS APIs used for ElectricEye CSPM and EASM assessments - Managed by CloudFormation StackSets
      Policies:
      - PolicyName: CrossAccountElectricEyeRolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - acm:DescribeCertificate
                - acm:ListCertificates
                - access-analyzer:ListAnalyzers
                - amplify:ListApps
                - airflow:GetEnvironment
                - airflow:ListEnvironments
                - apigateway:GET
                - appmesh:DescribeMesh
                - appmesh:DescribeVirtualNode
                - appmesh:ListMeshes
                - appmesh:ListVirtualNodes
                - apprunner:DescribeService
                - apprunner:DescribeWebAclForService
                - apprunner:ListServices
                - appstream:Describe*
                - athena:GetWorkGroup
                - athena:ListWorkGroups
                - autoscaling:DescribeAutoScalingGroups
                - backup:DescribeProtectedResource
                - bedrock:List*
                - cassandra:Select
                - cloud9:DescribeEnvironments
                - cloud9:ListEnvironments
                - cloudformation:DescribeStacks
                - cloudformation:ListStacks
                - cloudfront:GetDistribution
                - cloudfront:ListDistributions
                - cloudhsm:DescribeBackups
                - cloudhsm:DescribeClusters
                - cloudsearch:DescribeDomainEndpointOptions
                - cloudsearch:DescribeDomains
                - cloudtrail:DescribeTrails
                - cloudtrail:GetEventSelectors
                - cloudtrail:ListTrails
                - cloudtrail:LookupEvents
                - cloudwatch:DescribeAlarms
                - cloudwatch:GetMetricData
                - cloudwatch:DescribeAlarmsForMetric
                - codeartifact:GetDomainPermissionsPolicy
                - codeartifact:GetRepositoryPermissionsPolicy
                - codeartifact:ListDomains
                - codeartifact:ListRepositories
                - codebuild:BatchGetProjects
                - codebuild:ListProjects
                - codebuild:ListSourceCredentials
                - codedeploy:GetDeploymentGroup
                - codedeploy:ListApplications
                - codedeploy:ListDeploymentGroups
                - cognito-idp:DescribeUserPool
                - cognito-idp:GetWebACLForResource
                - cognito-idp:ListUserPools
                - datasync:DescribeAgent
                - datasync:DescribeTask
                - datasync:ListAgents
                - datasync:ListTasks
                - dax:DescribeClusters
                - dax:DescribeParameters
                - detective:ListGraphs
                - dms:DescribeReplicationInstances
                - ds:DescribeDirectories
                - ds:ListLogSubscriptions
                - dynamodb:DescribeContinuousBackups
                - dynamodb:DescribeTable
                - dynamodb:ListTables
                - ec2:Describe*
                - ec2:Get*
                - ecr:Describ*
                - ecr:GetLifecyclePolicy
                - ecr:GetRegistryPolicy
                - ecr:GetRepositoryPolicy
                - ecs:DescribeClusters
                - ecs:DescribeTaskDefinition
                - ecs:ListClusters
                - ecs:ListTaskDefinitionFamilies
                - ecs:ListTaskDefinitions
                - eks:DescribeCluster
                - eks:ListClusters
                - elasticache:DescribeCacheClusters
                - elasticbeanstalk:DescribeConfigurationSettings
                - elasticbeanstalk:DescribeEnvironments
                - elasticfilesystem:DescribeFileSystemPolicy
                - elasticfilesystem:DescribeFileSystems
                - elasticloadbalancing:DescribeL*
                - elasticmapreduce:DescribeCluster
                - elasticmapreduce:DescribeSecurityConfiguration
                - elasticmapreduce:GetBlockPublicAccessConfiguration
                - elasticmapreduce:ListClusters
                - elastictranscoder:ListPipelines
                - elastictranscoder:ReadPipeline
                - emr-serverless:GetApplication
                - emr-serverless:ListApplications
                - es:DescribeElasticsearchDomain
                - es:ListDomainNames
                - ecs:DescribeClusters
                - ecs:ListClusters
                - firehose:DescribeDeliveryStream
                - firehose:ListDeliveryStreams
                - firehose:Put*
                - fis:GetExperimentTemplate
                - fis:ListExperimentTemplates
                - fsx:DescribeBackups
                - fsx:DescribeFileSystems
                - glue:GetCrawler
                - glue:GetDataCatalogEncryptionSettings
                - glue:GetResourcePolicy
                - glue:GetSecurityConfiguration
                - glue:ListCrawlers
                - globalaccelerator:DescribeAcceleratorAttributes
                - globalaccelerator:List*
                - guardduty:ListD*
                - guardduty:ListIPSets
                - guardduty:GetD*
                - health:DescribeEvents
                - iam:GetAccessKeyLastUsed
                - iam:GetAccount*
                - iam:GetGroupPolicy
                - iam:GetPolicyVersion
                - iam:GetRolePolicy
                - iam:GetUserPolicy
                - iam:List*
                - imagebuilder:GetImage*
                - imagebuilder:ListImage*
                - inspector2:BatchGetAccountStatus
                - inspector2:GetConfiguration
                - inspector2:GetEc2DeepInspectionConfiguration
                - inspector2:ListCov*
                - inspector2:ListFind*
                - kafka:DescribeCluster
                - kafka:ListClusters
                - kinesis:DescribeStream
                - kinesis:ListStreams
                - kinesisanalytics:ListApplications
                - kms:Decrypt
                - kms:DescribeKey
                - kms:ListAliases
                - kms:ListKeys
                - lambda:GetFunction
                - lambda:GetLayerVersion
                - lambda:GetLayerVersionPolicy
                - lambda:GetPolicy
                - lambda:ListFunctions
                - lambda:ListLayer*
                - license-manager:GetLicenseConfiguration
                - license-manager:ListLicenseConfigurations
                - logs:DescribeLogGroups
                - logs:DescribeMetricFilters
                - logs:DescribeSubscriptionFilters
                - logs:ListLogDeliveries
                - macie2:GetMacieSession
                - managedblockchain:Get*
                - managedblockchain:List*
                - memorydb:Describe*
                - mq:Describe*
                - mq:List*
                - qbusiness:L*
                - qldb:ListJournalS3Exports
		- qbusiness:D*
                - qldb:ListLedgers
                - ram:GetResourceShares
                - rds:DescribeDB*
                - rds:DescribeEvent*
                - redshift:DescribeCluster*
                - redshift:DescribeLoggingStatus
                - redshift-serverless:ListNamespaces
                - redshift-serverless:ListWorkgroups
                - route53:List*
                - route53resolver:GetFirewallConfig
                - route53resolver:List*
                - rolesanywhere:List*
                - s3:GetAccountPublicAccessBlock
                - s3:GetBucketLogging
                - s3:GetBucketPol*
                - s3:GetBucketVersioning
                - s3:GetEncryptionConfiguration
                - s3:GetLifecycleConfiguration
                - s3:ListAllMyBuckets
                - s3:ListBucket
                - sagemaker:Describe*
                - sagemaker:List*
                - secretsmanager:ListSecrets
                - securityhub:BatchIm*
                - securityhub:DescribeHub
                - shield:Describ*
                - shield:ListA*
                - sns:GetTopicAttributes
                - sns:ListSub*
                - ssm:ListDocuments
                - ssm:ListAssociations
                - ssm:DescribeDocumentPermission
                - ssm:DescribeInstance*
                - ssm:GetP*
                - sns:ListTopics
                - sqs:GetQueueAttributes
                - sqs:ListQueues
                - support:DescribeTrustedA*
                - vpc-lattice:Get*
                - vpc-lattice:List*
                - wafv2:GetLogging*
                - wafv2:GetWeb*
                - wafv2:ListW*
                - workspaces:DescribeWorkspaceDirectories
                - workspaces:DescribeWorkspaces
                - xray:GetEncryptionConfig
              Resource: "*"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${CentralSecurityAccount}'
            Action:
              - sts:AssumeRole
      Tags: 
        - 
          Key: Name
          Value: CrossAccountElectricEyeRole
        - 
          Key: Service
          Value: ElectricEye
# END